import {
  LOGO_LIBRARY_COMPETITIONS,
  LOGO_LIBRARY_TEAMS,
} from "@/lib/logo-library-index";
import {
  GLOBAL_TEAM_METADATA_OVERRIDES,
  TEAM_COMPETITION_DISPLAY_NAME_OVERRIDES,
  TEAM_DISPLAY_NAME_OVERRIDES,
} from "@/lib/team-metadata-overrides";

export const CLUB_CATALOG = [
  {
    competition: "Liga Nacional",
    clubs: [
      "Argentino de Junín",
      "Atenas de Córdoba",
      "Boca Juniors",
      "Ferro Carril Oeste",
      "Gimnasia y Esgrima de Comodoro Rivadavia",
      "Independiente de Oliva",
      "Instituto de Córdoba",
      "La Unión de Formosa",
      "Oberá Tenis Club",
      "Obras Basket",
      "Olímpico de la Banda",
      "Peñarol de Mar del Plata",
      "Platense",
      "Quimsa",
      "Regatas Corrientes",
      "Riachuelo",
      "San Lorenzo de Almagro",
      "San Martín de Corrientes",
      "Unión de Santa Fe",
      "Zárate Basket",
    ],
  },
  {
    competition: "Liga Próximo",
    clubs: [
      "Argentino de Junín",
      "Atenas de Córdoba",
      "Boca Juniors",
      "Ferro Carril Oeste",
      "Gimnasia y Esgrima de Comodoro Rivadavia",
      "Independiente de Oliva",
      "Instituto de Córdoba",
      "La Unión de Formosa",
      "Oberá Tenis Club",
      "Obras Basket",
      "Olímpico de la Banda",
      "Peñarol de Mar del Plata",
      "Platense",
      "Quimsa",
      "Regatas Corrientes",
      "Riachuelo",
      "San Lorenzo de Almagro",
      "San Martín de Corrientes",
      "Unión de Santa Fe",
      "Zárate Basket",
    ],
  },
  {
    competition: "Euroliga",
    clubs: [
      "Anadolu Efes Istanbul",
      "AS Monaco",
      "Crvena Zvezda Meridianbet Belgrade",
      "Dubai Basketball",
      "EA7 Emporio Armani Milan",
      "FC Barcelona",
      "FC Bayern Munich",
      "Fenerbahçe Beko Istanbul",
      "Hapoel IBI Tel Aviv",
      "Kosner Baskonia Vitoria-Gasteiz",
      "LDLC ASVEL Villeurbanne",
      "Maccabi Rapyd Tel Aviv",
      "Olympiacos Piraeus",
      "Panathinaikos AKTOR Athens",
      "Paris Basketball",
      "Partizan Mozzart Bet Belgrade",
      "Real Madrid",
      "Valencia Basket",
      "Virtus Bologna",
      "Žalgiris Kaunas",
    ],
  },
  {
    competition: "Liga Argentina",
    clubs: [
      "Amancay de La Rioja",
      "Barrio Parque",
      "Bochas Sport Club",
      "Centenario de Venado Tuerto",
      "Colón de Santa Fe",
      "Comunicaciones de Mercedes",
      "Central Entrerriano",
      "Club Atlético Pilar",
      "Club Atlético Estudiantes de Tucumán",
      "Deportivo Norte",
      "Deportivo Viedma",
      "Gimnasia y Esgrima de La Plata",
      "Hispano Americano",
      "Huracán Las Heras",
      "Hindú Club de Córdoba",
      "Independiente BBC",
      "Jujuy Básquet",
      "La Unión de Colón",
      "Lanús",
      "Montmartre",
      "Pico Football Club",
      "Provincial de Rosario",
      "Quilmes de Mar del Plata",
      "Racing de Avellaneda",
      "Racing de Chivilcoy",
      "Rivadavia Básquet",
      "Salta Basket",
      "Atlético San Isidro",
      "Sportivo Suardi",
      "Tomás de Rocamora",
      "Talleres de Tafí Viejo",
      "Unión de Mar del Plata",
      "Villa Mitre de Bahía Blanca",
      "Villa San Martín de Resistencia",
    ],
  },
  {
    competition: "Liga Federal",
    clubs: [
      "9 de Julio de Morteros",
      "Alejandro Korn",
      "All Boys de Santa Rosa",
      "Alma Juniors de Esperanza",
      "Almafuerte de Las Varillas",
      "Almagro de Esperanza",
      "APV",
      "Argentino de Marcos Juárez",
      "Asociación Chamicalense",
      "Asociación Mitre",
      "Atenas de La Plata",
      "Atlético Riojano",
      "Atlético de Rafaela",
      "Atlético Regina",
      "Atlético Sastre",
      "Atlético Tostado",
      "Banda Norte",
      "Banco Rioja",
      "Belgrano Cultural y Deportivo",
      "Belgrano de San Nicolás",
      "Bochas Sport Club",
      "CAPRI de Posadas",
      "Casa de Padua",
      "Caza y Pesca",
      "Centro Español de Plottier",
      "CEPA",
      "Central Argentino",
      "Ciudad de Campana",
      "Claridad",
      "Club Atlético Pilar",
      "Concepción BB",
      "Córdoba de Corrientes",
      "Cultural de Santa Sylvina",
      "Deportivo Español",
      "Deportivo Plottier",
      "Deportivo Roca",
      "Don Bosco de Resistencia",
      "El Biguá",
      "El Carmen de Perico",
      "El Ceibo",
      "El Tala",
      "Estudiantes de La Plata",
      "Estudiantes de Olavarría",
      "Estudiantil Porteño",
      "Facundo",
      "Ferro de General Pico",
      "G.E.P.U. de San Luis",
      "GEVP",
      "Gimnasia y Esgrima de Ituzaingó",
      "Gimnasia y Esgrima de Rosario",
      "Gimnasia y Esgrima de Santa Fe",
      "Hércules de Charata",
      "Hindú Club de Resistencia",
      "Independiente de Avellaneda",
      "Independiente de General Pico",
      "Independiente de Neuquén",
      "Independiente de Tandil",
      "José Hernández",
      "La Armonía de Colón",
      "La Rioja Basket",
      "Los Indios de Moreno",
      "María Juana",
      "Matienzo de Córdoba",
      "Midland",
      "Mitre de Posadas",
      "Montmartre de Catamarca",
      "Morón",
      "Náutico Avellaneda",
      "Náutico Hacoaj",
      "Olimpia de Venado Tuerto",
      "Pacífico de Neuquén",
      "Pérfora de Plaza Huincul",
      "Petrolero Argentino de Plaza Huincul",
      "Pinocho",
      "Presidente Derqui",
      "Quique Club de Paraná",
      "Racing de Olavarría",
      "Red Star de Catamarca",
      "Regatas de Resistencia",
      "Regatas de San Nicolás",
      "Rivadavia Juniors de Santa Fe",
      "River Plate",
      "Rosario Central",
      "San Andrés",
      "San Fernando",
      "San Lorenzo de Monte Caseros",
      "San Martín de Marcos Juárez",
      "San Miguel",
      "Sanjustino",
      "Sionista",
      "Somisa de San Nicolás",
      "Sportivo Escobar",
      "Sportivo Pilar",
      "Sparta de Villa María",
      "Talleres de Tafí Viejo",
      "Temperley de Rosario",
      "Tokio de Posadas",
      "Tres de Febrero",
      "Unión de Oncativo",
      "Unión Central de Villa María",
      "Unión Vecinal de Munro",
      "Unión y Juventud de Bandera",
      "Urquiza de San Juan",
      "Urquiza de Santa Elena",
    ],
  },
  {
    competition: "Liga Metropolitana",
    clubs: [
      "Club Tres de Febrero",
      "Alejandro Korn",
      "Argentino de Castelar",
      "Asociación Vecinal de Pilar",
      "Berazategui",
      "Cañuelas Fútbol Club",
      "Caza y Pesca",
      "CEPA",
      "Ciudad de Buenos Aires",
      "Claridad",
      "Defensores de Hurlingham",
      "Estudiantil Porteño",
      "Ezeiza",
      "Gimnasia y Esgrima de Ituzaingó",
      "Gimnasia y Esgrima de La Plata",
      "Independiente",
      "Las Heras de Villa Ballester",
      "Los Andes",
      "Los Indios de Moreno",
      "Midland",
      "Monte Grande",
      "Moreno de Quilmes",
      "Morón",
      "Náutico Hacoaj",
      "Nolting",
      "Casa de Padua",
      "Obras Basket",
      "Presidente Derqui",
      "River Plate",
      "San Andrés",
      "San Fernando",
      "San Miguel",
      "Sportivo Escobar",
      "Sportivo Pilar",
      "Unión Vecinal de Munro",
      "Universidad Nacional de La Matanza",
      "Vélez Sarsfield",
    ],
  },
  {
    competition: "Liga Femenina",
    clubs: [
      "Bochas Sport Club",
      "Chañares de James Craik",
      "Deportivo Berazategui",
      "El Biguá",
      "El Talar",
      "Ferro Carril Oeste",
      "Gorriones de Río Cuarto",
      "Hindú Club de Córdoba",
      "Independiente de Neuquén",
      "Instituto de Córdoba",
      "Lanús",
      "Náutico Sportivo Avellaneda",
      "Obras Basket",
      "Quimsa",
      "Riachuelo",
      "Tomás de Rocamora",
      "San José de Mendoza",
      "Unión Florida",
    ],
  },
  {
    competition: "Liga Ecuador Fem",
    clubs: [
      "Atuneros del Pacífico",
      "Cuenca",
      "Dragonas Importadora Alvarado",
      "Jorge Guzmán",
      "Piratas",
      "San Antonio",
      "Spartans",
    ],
  },
] as const;

export const LIGA_ARGENTINA_OFFTUBE_CONTACTS = [
  "Ciclista Juninense",
  "Villa San Martín de Resistencia",
  "Huracán Las Heras",
  "Comunicaciones de Mercedes",
  "Tomás de Rocamora",
  "Rivadavia Básquet",
  "Pergamino Básquet",
  "La Unión de Colón",
  "Santa Paula de Gálvez",
  "Bochas Sport Club",
  "Club Atlético Estudiantes de Tucumán",
  "Centenario de Venado Tuerto",
  "Jujuy Básquet",
  "Central Entrerriano",
  "Salta Basket",
] as const;

export const ADDITIONAL_COMPETITIONS = [
  "ABB",
  "Amistosos",
  "BCLA",
  "Liga Desarrollo",
  "Liga Sudamericana Masc.",
  "Super 20",
  "Amistoso Selección Argentina",
  "Tour 3x3",
  "Metro 3x3",
  "Circuito 3x3",
  "La Liga 3x3",
  "Liga Metropolitana Fem",
  "Supercopa",
] as const;

export const INACTIVE_SEASON_COMPETITIONS = [
  "Liga Brasil LDB",
  "Liga Brasil NBB",
] as const;

const INACTIVE_SEASON_COMPETITION_SET = new Set<string>(INACTIVE_SEASON_COMPETITIONS);

export const LOGO_COMPETITIONS = [
  "Euroliga",
  "LBA Serie A",
  "LBP Femenina",
  "LBP Masculina",
  "LDA",
  "LNF Chile",
  "LUB",
  "Libo Basquet",
  "Liga 3x3",
  "Liga Chery",
  "Liga Dos",
  "Liga Endesa",
  "Liga Metro",
  "Liga Nacional",
  "Liga Proximo",
  "Liga U22",
  "Primera FEB",
  "Super Copa Endesa",
] as const;

export const CLUB_COMPETITIONS = Array.from(
  new Set([
    ...CLUB_CATALOG.map((entry) => entry.competition),
    ...ADDITIONAL_COMPETITIONS,
    ...LOGO_COMPETITIONS,
    ...LOGO_LIBRARY_COMPETITIONS,
  ]),
).filter(
  (competition) => !INACTIVE_SEASON_COMPETITION_SET.has(competition),
);

function getClubDisplayName(clubName: string) {
  return (
    TEAM_DISPLAY_NAME_OVERRIDES[clubName]?.trim() ||
    GLOBAL_TEAM_METADATA_OVERRIDES[clubName]?.display_name?.trim() ||
    clubName
  );
}

export const ALL_CLUB_OPTIONS = Array.from(
  new Set([
    ...CLUB_CATALOG.flatMap((entry) => entry.clubs.map(getClubDisplayName)),
    ...LIGA_ARGENTINA_OFFTUBE_CONTACTS.map(getClubDisplayName),
    ...LOGO_LIBRARY_TEAMS.map(getClubDisplayName),
    ...Object.values(TEAM_DISPLAY_NAME_OVERRIDES),
    ...Object.values(TEAM_COMPETITION_DISPLAY_NAME_OVERRIDES),
  ]),
);
