// Generated from public/LogosPNG by local tooling.
export type LogoLibraryLeague = {
  competition: string;
  folder: string;
  aliases: string[];
  teams: string[];
};

export const LOGO_LIBRARY_INDEX: LogoLibraryLeague[] = [
  {
    competition: "Euroliga",
    folder: "Logos EuroLiga 500 x 500",
    aliases: ["euroleague"],
    teams: [
      "Anadolu Efes Istanbul",
      "AS Monaco",
      "Crvena Zvezda Meridianbet Belgrade",
      "Dubai Basketball",
      "EA7 Emporio Armani Milan",
      "FC Barcelona",
      "FC Bayern Munich",
      "Fenerbahçe Beko Istanbul",
      "Hapoel IBI Tel Aviv",
      "LDLC ASVEL Villeurbanne",
      "Maccabi Playtika Tel Aviv",
      "Olympiacos Piraeus",
      "Panathinaikos AKTOR Athens",
      "Paris Basketball",
      "Partizan Mozzart Bet Belgrade",
      "Valencia Basket",
      "Žalgiris Kaunas",
    ],
  },
  {
    competition: "Liga Argentina",
    folder: "Logos Liga Argentina 500 x 500",
    aliases: ["contactos liga argentina offtube"],
    teams: [
      "Amancay de La Rioja",
      "Atlético San Isidro",
      "Barrio Parque",
      "Bochas Sport Club",
      "Centenario de Venado Tuerto",
      "Central Entrerriano",
      "Ciclista Juninense",
      "Club Atlético Estudiantes de Tucumán",
      "Club Atlético Estudiantes",
      "Club Atlético Provincial",
      "Colón SF",
      "Comunicaciones de Mercedes",
      "Deportivo Norte",
      "Deportivo Viedma",
      "El Talar",
      "Fusión Riojana",
      "Gimnasia",
      "Hindú Club",
      "Hispano Americano",
      "Huracán Las Heras",
      "Independiente BBC",
      "Jujuy Básquet",
      "La Unión de Colón",
      "Lanús",
      "Pergamino Básquet",
      "Pico Football Club",
      "Quilmes de Mar del Plata",
      "Racing de Avellaneda",
      "Rivadavia Básquet",
      "Salta Basket",
      "Santa Paula de Gálvez",
      "Sportivo Suardi",
      "Tomás de Rocamora",
      "Unión de Mar del Plata",
      "Villa Mitre de Bahía Blanca",
      "Villa San Martín de Resistencia",
    ],
  },
  {
    competition: "Libo Basquet",
    folder: "Logos Liga Bolivia 500 x 500",
    aliases: ["liga bolivia"],
    teams: [
      "Calero",
      "Can",
      "Carl AZ",
      "Kinwa",
      "Leones",
      "Pichincha",
      "Potosi",
      "U Sucre",
    ],
  },
  {
    competition: "Liga Brasil LDB",
    folder: "Logos Liga Brasil LDB 500 X 500",
    aliases: [],
    teams: [
      "ADRM",
      "Basket Osasco",
      "Bauru",
      "Botafogo",
      "Brasília Basquete",
      "Campo Mourao",
      "Caxias",
      "Cearense",
      "Corinthians",
      "Cruzeiro",
      "Flamengo",
      "Franca",
      "Minas",
      "Mogi",
      "Pato",
      "Paulistano",
      "Pinheiros",
      "Soc.Thalia",
      "Sorocabana",
      "São José Basketball",
      "São Paulo",
      "Unico",
      "Unifacisa",
      "Vasco",
      "Vitória",
    ],
  },
  {
    competition: "Liga Brasil NBB",
    folder: "Logos Liga Brasil NBB 500 X 500",
    aliases: [],
    teams: [
      "Basket Osasco",
      "Bauru",
      "Botafogo",
      "Brasília Basquete",
      "Caxias",
      "Corinthians",
      "Cruzeiro",
      "Flamengo",
      "Fortaleza Basquete Cearense",
      "Franca",
      "Kto Minas",
      "Minas",
      "Mogi",
      "Pato",
      "Paulistano",
      "Pinheiros",
      "Rio Claro",
      "Sorocabana",
      "São José Basketball",
      "São Paulo",
      "Unico",
      "Unifacisa",
      "Vasco",
      "Vitória",
    ],
  },
  {
    competition: "Liga Chery",
    folder: "Logos Liga Chery Chile 500 x 500",
    aliases: ["liga uno chery", "liga chery chile"],
    teams: [
      "ABA Ancud",
      "Boston College",
      "Club Deportivo Valdivia",
      "Colegio Los Leones",
      "Colo Colo",
      "Deportes Castro",
      "Español de Talca",
      "Español Osorno",
      "Gimnástico",
      "Las Ánimas",
      "Puente Alto",
      "Puerto Varas",
      "Santiago Morning Quilicura",
      "Sportivo Italiano",
      "Universidad Católica",
      "Universidad de Concepción",
    ],
  },
  {
    competition: "Liga Dos",
    folder: "Logos Liga Dos Chile 500 x 500",
    aliases: ["liga dos chile"],
    teams: [
      "Aleman",
      "Brisas",
      "Constitucion",
      "Huachipato",
      "Illapel Básquetbol",
      "Liceo Curico",
      "Luis Matte",
      "Municipal Chillán",
      "Omega",
      "Pratt",
      "Puerto Montt",
      "Quilpué Básquetbol",
      "Sergio Ceppi",
      "Sharks",
      "Sportivo Italiano",
      "Stadio Italiano",
      "Temuco",
      "Tinguiririca",
      "Truenos de Talca",
      "Árabe de Valparaíso",
    ],
  },
  {
    competition: "LDA",
    folder: "Logos Liga Ecuador 500 x 500",
    aliases: [],
    teams: [
      "Barcelona Sporting Club",
      "Cuenca",
      "Guerreros",
      "Importadora Alvarado",
      "Jorge Guzmán",
      "Leones de Riobamba",
      "Piratas de los Lagos",
      "San Antonio",
      "Spartans",
      "Zamora",
    ],
  },
  {
    competition: "Liga Ecuador Fem",
    folder: "Logos Liga Ecuador Fem 500 x 500",
    aliases: [],
    teams: [
      "Atuneros del Pacífico",
      "Cuenca",
      "Dragonas Importadora Alvarado",
      "Jorge Guzmán",
      "Piratas de los Lagos",
      "San Antonio Gold",
      "Spartans",
    ],
  },
  {
    competition: "Liga Endesa",
    folder: "Logos Liga Endesa 500 x 500",
    aliases: ["acb"],
    teams: [
      "Barça",
      "Baskonia",
      "BAXI Manresa",
      "Bàsquet Girona",
      "Casademont Zaragoza",
      "Coviran Granada",
      "Dreamland Gran Canaria",
      "Hiopos Lleida",
      "Joventut Badalona",
      "La Laguna Tenerife",
      "Leyma Coruña",
      "MoraBanc Andorra",
      "Real Madrid",
      "Río Breogán",
      "San Pablo Burgos",
      "Surne Bilbao Basket",
      "Unicaja",
      "Valencia Basket",
    ],
  },
  {
    competition: "Liga Femenina",
    folder: "Logos Liga Femenina 500 x 500",
    aliases: ["liga metropolitana fem"],
    teams: [
      "Bochas Sport Club",
      "Chañares de James Craik",
      "Deportivo Berazategui",
      "El Biguá",
      "El Talar",
      "Ferro Carril Oeste",
      "Fusión Riojana",
      "Gorriones de Río Cuarto",
      "Hindú (C)",
      "Independiente (N)",
      "Instituto de Córdoba",
      "Lanús",
      "Montmartre",
      "Náutico (R)",
      "Obras",
      "Olimpico",
      "Peñarol",
      "Quimsa",
      "Riachuelo",
      "San José de Mendoza",
      "Tomás de Rocamora",
      "Union deportiva San jose",
      "Unión Florida",
    ],
  },
  {
    competition: "LBA Serie A",
    folder: "Logos Liga Italia 500 x 500",
    aliases: ["lba"],
    teams: [
      "Brescia",
      "Cremona",
      "Dinamo Sassari",
      "Dolomiti Energia Trentino",
      "Givova Scafati",
      "Napoli",
      "Nutribullet Treviso",
      "Olimpia Milano",
      "Openjobmetis Varese",
      "Pallacanestro Cantù",
      "Pallacanestro Udinese",
      "Pesaro",
      "Pistoia",
      "Tortona",
      "Trapani",
      "Treviso",
      "Trieste",
      "Umana Reyer Venezia",
      "UNA Hotels Reggio Emilia",
      "Virtus Bologna",
    ],
  },
  {
    competition: "LNF Chile",
    folder: "Logos Liga LNF Chile 500 x 500",
    aliases: [],
    teams: [
      "Azul y Rojo",
      "Colegio Los Leones",
      "Gimnástico",
      "Puente Alto",
      "Santiago Morning Quilicura",
      "Sergio Ceppi",
      "Sportivo Italiano",
      "Universidad de Concepción",
    ],
  },
  {
    competition: "Liga Metropolitana",
    folder: "Logos Liga Metroplitana 500 x 500",
    aliases: ["liga metro"],
    teams: [
      "Alejandro Korn",
      "Argentino Castelar",
      "Ateneo Popular Versailles",
      "Casa de Padua",
      "Caza y Pesca",
      "Cañuelas Fútbol Club",
      "CEPA",
      "Ciudad de Buenos Aires",
      "Claridad",
      "Club GEI",
      "Club Tres de Febrero",
      "Defensores de Hurlingham",
      "Estudiantil porteño",
      "Ezeiza",
      "Gimnasia de Villa del Parque",
      "Gimnasia y Esgrima de La Plata",
      "Independiente",
      "Jose Hernandez",
      "Las Heras de Villa Ballester",
      "Los Andes",
      "Los Indios de Moreno",
      "Midland",
      "Monte Grande",
      "Moreno de Quilmes",
      "Morón",
      "Nolthing",
      "Nolting",
      "Náutico Hacoaj",
      "Obras Basket",
      "Pinocho",
      "Presidente Derqui",
      "River Plate",
      "San Andrés",
      "San Fernando",
      "San Miquel",
      "Sportivo Escobar",
      "Sportivo Pilar",
      "Universidad La Matanza",
      "Unión Vecinal de Munro",
      "Velez Sarsfield",
    ],
  },
  {
    competition: "Liga Nacional",
    folder: "Logos Liga Nacional 500 x 500",
    aliases: ["liga proximo"],
    teams: [
      "Argentino (J)",
      "Atenas de Córdoba",
      "Boca Juniors",
      "Ferro Carril Oeste",
      "Gimnasia y Esgrima de Comodoro Rivadavia",
      "Independiente de Oliva",
      "Instituto de Córdoba",
      "La Unión (F)",
      "Oberá Tenis Club",
      "Obras",
      "Olímpico de la Banda",
      "Peñarol de Mar del Plata",
      "Platense",
      "Quimsa",
      "Racing de Chivilcoy",
      "Regatas (C)",
      "Riachuelo",
      "San Lorenzo de Almagro",
      "San Martín (C)",
      "Unión de Santa Fe",
      "Zarate",
    ],
  },
  {
    competition: "LUB",
    folder: "Logos Liga Uruguay 500 x 500",
    aliases: [],
    teams: [
      "Aguada",
      "Biguá",
      "Cordón",
      "Defensor Sporting",
      "Goes",
      "Hebraica",
      "Larre Borges",
      "Malvín",
      "Nacional",
      "Peñarol Uru",
      "Trouville",
      "Unión Atlética",
      "Urunday",
      "Urupan",
      "Welcome",
    ],
  },
  {
    competition: "LUB Ascenso",
    folder: "Logos Liga Uruguay Ascenso 500 x 500",
    aliases: ["liga uruguay ascenso"],
    teams: [
      "Atlético Atenas",
      "Capitol",
      "Colón",
      "Lagomar",
      "Larragaña",
      "Larre Borges",
      "Marne",
      "Montevideo",
      "Olimpia",
      "Stockolmo",
      "Tabaré",
      "Verdirojo",
    ],
  },
  {
    competition: "Primera FEB",
    folder: "Logos Primera FEB 500 x500",
    aliases: [],
    teams: [
      "Alega Cantabria",
      "Alimerka Oviedo Baloncesto",
      "Amics Castelló",
      "Caja Rural CB Zamora",
      "Cartagena",
      "CB Naturavia Morón",
      "Club Ourense Baloncesto",
      "FIBWI Mallorca Basquet",
      "Flexicar Fuenlabrada",
      "Grupo Alega Cantabria",
      "Grupo Ureta Tizona Burgos",
      "Hestia Menorca",
      "HLA Alicante",
      "Inveready Gipuzkoa",
      "Melilla Ciudad Del Deporte",
      "Monbus Obradoiro",
      "Movistar Estudiantes",
      "Palencia Baloncesto",
      "Palmer Basket Mallorca Palma",
      "Real Betis Baloncesto",
      "UEMC Real Valladolid",
    ],
  },
  {
    competition: "Liga U22",
    folder: "Logos U22 España",
    aliases: [],
    teams: [
      "Amara Lleida",
      "Basquet Girona",
      "BAXI Manresa",
      "Bilbao Basket",
      "Casademont Zaragoza",
      "FC Barcelona",
      "Fundación CB Canarias",
      "Gran Canaria",
      "Joventut Badalona",
      "La Laguna Tenerife",
      "Real Madrid",
      "San Pablo Burgos",
      "Stellantis & You Granada",
      "UCAM Murcia",
      "Unicaja",
      "Valencia Basket",
      "Zamora",
    ],
  },
];

export const LOGO_LIBRARY_COMPETITIONS = LOGO_LIBRARY_INDEX.map((entry) => entry.competition);
export const LOGO_LIBRARY_TEAMS = Array.from(
  new Set(LOGO_LIBRARY_INDEX.flatMap((entry) => entry.teams)),
);
